Form/ContainerType.php
<?php

namespace Fuz\GenyBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ContainerType extends AbstractType
{

    /**
     * {@inheritdoc}
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'compound' => true,
        ));
    }

    /**
     * {@inheritdoc}
     */
    public function getParent()
    {
        return 'form';
    }

    /**
     * {@inheritdoc}
     */
    public function getName()
    {
        return 'container';
    }

}

Resources/views/macros.html.twig
{# GenyBundle::macros.html.twig #}

{% macro modal(id, title, body, footer) %}
    <div class="modal fade" id="{{ id }}" tabindex="-1" role="dialog" aria-labelledby="{{ id }}" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title"><div class="text-left">{{ title }}</div></h4>
                </div>
                <div class="modal-body">
                    {{ body }}
                </div>
                <div class="modal-footer">
                    <button
                        type="button"
                        class="btn btn-default"
                        data-dismiss="modal"
                        title="{{ 'geny.modal.close.title' | trans({}, 'geny') }}">
                        {{ 'geny.modal.close.value' | trans({}, 'geny') }}
                    </button>
                    {% if footer %}
                        {{ footer }}
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
{% endmacro %}

Resources/views/theme.html.twig
{# GenyBundle::theme.html.twig #}

{% block entry_label %}
{% endblock %}

{% block entry_widget %}
    <div class="row">
        <div class="col-md-5">
            {{ form_widget(form) }}
        </div>
        <div class="col-md-3">
            <a href="#" class="collection-up btn btn-default" title="Move element up"><span class="glyphicon glyphicon-arrow-up"></span></a>
            <a href="#" class="collection-down btn btn-default" title="Move element down"><span class="glyphicon glyphicon-arrow-down"></span></a>
        </div>
        <div class="col-md-3">
            {% if form.parent.vars.allow_delete %}
                <a href="#" class="collection-delete btn btn-default" title="Delete element"><span class="glyphicon glyphicon-trash"></span></a>
            {% endif %}
            {% if form.parent.vars.allow_add %}
                <a href="#" class="collection-add btn btn-default" title="Add element"><span class="glyphicon glyphicon-plus-sign"></span></a>
            {% endif %}
        </div>
        <div class="col-md-1">
            <a href="#" class="collection-duplicate btn btn-default" title="Duplicate element"><span class="glyphicon glyphicon-th-large"></span></a>
        </div>
    </div>
{% endblock %}